### ISSUE TITLE
Code for detecting electromagnetic crosstalk

### ISSUE THREAD

**Issue by RonaldAJ** [larsimmisch/pyalsaaudio#102]
Dear Lars,

I have written scripts to record sound which will show electromagnetic crosstalk from Wi-Fi or the recording electronics to the microphone. It will be accompanied by a short note (paper would be too much honour for this piece of text). For an early preview: https://github.com/soundappraisal/pyalsaaudio/tree/Establishing_electro_magnetic_crosstalk. 

Is it something you would consider to include in the library, or is it better to give it its own repo?

Kind regards,
Ronald

**Comment by larsimmisch** [comment]
Hi Ronald,

I don't have a strong opinion, TBH. But for the purposes of your paper, a separate repo (maybe with a pyalsaaudio submodule for easier installation) might be better, no?

- Lars

**Comment by ossilator** [comment]
this seems way too high-level.
i suppose one could link it somewhere in the documentation, but there is *a lot* of other code one could link as well.
so, out of scope imo.

**Comment by RonaldAJ** [comment]
I'll move it elsewhere.
