### ISSUE TITLE
Extend names from 32 to 64 (or more) characters

### ISSUE THREAD

**Issue by dmoimas** [larsimmisch/pyalsaaudio#114]
Hello,

I have some CODECs that have enum controls with very long values (i.e. TI PCM5122 on DSP Control) which are truncated due to limit in 32 characters. I'd like to have those arrays extended to 64chars or more on official release. 

BR,
 Diego

**Comment by dmoimas** [comment]
Hi Lars, thanks so much.

Also name[32] on get_enum must be extended as the enum control has very loong values (see pcm512x.c in /sound/soc/codecs of kernel source)

**Comment by larsimmisch** [comment]
Thanks, fixed.
