### ISSUE TITLE
convert input np float32

### ISSUE THREAD

**Issue by StuartIanNaylor** [larsimmisch/pyalsaaudio#121]
I have been struggling with sounddevice as for some reason doesn't list Alsa pcms
With sounddevice the datatype is float `sd.default.dtype= ('float32', 'float32')`

So I have
```
  inp = alsaaudio.PCM(alsaaudio.PCM_CAPTURE, alsaaudio.PCM_NONBLOCK, 
		channels=1, rate=sample_rate, format=alsaaudio.PCM_FORMAT_FLOAT_LE, 
		periodsize=rec_samples, device=device)


  while True:
    # Read data from device
    l, data = inp.read()

    if l:
      #print(data)
      rec = np.frombuffer(data, dtype=np.float32)
      #print(rec)
      inf = inference(rec)
      #if inf[0] > 0.90:
      print(inf[0])
      time.sleep(.001)
```

can anyone help to tell me what alsa format I should use and how to convert that to a np float32?
Thnx & apols

**Comment by larsimmisch** [comment]
I'd probably try `PCM_FORMAT_S16_LE` and convert that to a float. This might be relevant: https://stackoverflow.com/questions/14513775/going-from-signed-pcm-format-s16-le-to-floating-point-number-in-python
