### ISSUE TITLE
Mixer.getvolume|setvolume percentage inconsistency?

### ISSUE THREAD

**Issue by rnixx** [larsimmisch/pyalsaaudio#124]
Getting and setting volume on mixer by percentage not matches the percentage value displayed in `alsamixer`. Is this by intention and if so, why?

![Bildschirmfoto von 2023-02-25 10-53-14](https://user-images.githubusercontent.com/246021/221351037-1031f881-d7fd-4436-be56-a383e497f35e.png)

**Comment by diederikdq** [comment]
Hi @rnixx ,
What percentage values do you get when you run:
```
amixer -M get Master
``` 
VS
```
amixer get Master
``` 
I had the same question about a month ago and found https://bbs.archlinux.org/viewtopic.php?pid=1114261#p1114261 
I can only share my findings when I tried to understand the different values.

**Comment by ossilator** [comment]
the link provided above nails it: alsamixer uses a different scale than amixer and pyalsaaudio (logarithmic vs. linear).
