### ISSUE TITLE
getvolume() returns outdated volume value

### ISSUE THREAD

**Issue by dhansmair** [larsimmisch/pyalsaaudio#126]
Hi! thank you for the great tool.

I'm having a problem on my laptop:
```
Python 3.10.10 (main, Mar  5 2023, 22:26:53) [GCC 12.2.1 20230201] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import alsaaudio
>>> mixer = alsaaudio.Mixer()
>>> mixer.getvolume()
[46, 46]
>>> mixer.getvolume()
[46, 46]
>>> 
```

the first time, I'm getting the correct volume as expected. Then, I change the volume using the keyboard volume keys.
Then, the second call to `mixer.getvolume()` returns the same value, even though the volume has changed by that time.
when instantiating the mixer again using `mixer = alsaaudio.Mixer()`, the correct volume is returned as expected.

Do you have an idea what could cause this problem?

**Comment by larsimmisch** [comment]
No good idea yet, but I can reproduce the issue here using a parallel session with alsamixer. I'll try to take a look.
