### ISSUE TITLE
Format of PCM Object

### ISSUE THREAD

**Issue by A622266** [larsimmisch/pyalsaaudio#128]
I am having trouble setting the format of the PCM object.  I have version 0.10.0.
```python
device = alsaaudio.PCM(alsaaudio.PCM_CAPTURE, alsaaudio.PCM_NORMAL, format=PCM_FORMAT_S16_LE)
```
results in:
```
NameError: name 'PCM_FORMAT_S16_LE' is not defined
```
My code will run if I don't include the format parameter (i.e. accept the default).  But I want to change the default to other data types.  Does anyone have advice?

**Comment by larsimmisch** [comment]
Oh, that’s just a missing `alsaaudio` namespace before  `PCM_FORMAT_S16_LE`. Try: `device = alsaaudio.PCM(alsaaudio.PCM_CAPTURE, alsaaudio.PCM_NORMAL, format=alsaaudio.  PCM_FORMAT_S16_LE)`

**Comment by A622266** [comment]
yes thank you.  That was quite an oversight!
