### ISSUE TITLE
misplaced 0.10 tag

### ISSUE THREAD

**Issue by ossilator** [larsimmisch/pyalsaaudio#140]
the tag for the 0.10.0 release is on no branch. this is confusing, and i presume that it was not intended. it can be fixed by simply merging the tag into the main branch.

**Comment by larsimmisch** [comment]
Yeah, that was probably an oversight.
 
I've invited you and @RonaldAJ as collaborators - feel free to fix the issue. I don't think much hinges on the exact semantics of that tag.

**Comment by ossilator** [comment]
it's in so far important that `git describe` has less to work with without the tag being on the branch.

i'll fix it.

**Comment by RonaldAJ** [comment]
> I've invited you and @RonaldAJ as collaborators 

I have accepted. Thanks for the trust!

**Comment by ossilator** [comment]
so did i, thanks.

let's agree on a few ground rules, though:
- we don't push directly, but post PRs for review. an exception to that can be pre-approved and/or obviously trivial changes, like this one.
- i'm a big fan of good commit hygiene. i'd use https://wiki.qt.io/Commit_Policy (as far as applicable) as a baseline, in particular point 8.

**Comment by larsimmisch** [comment]
Thanks.

As for the ground rules, thanks, that's a very good starting point. 
I'd like to add: _be excellent to each other_.

Regarding good commit hygiene: I'd love to be able to do it, but a) I learned coding before `cvs` was a thing b) refactoring *and* maintaining good commit hygiene is hard for me. Sorry, though.

**Comment by larsimmisch** [comment]
I've added a very small github branch protection rule: `main` should now be protected against force pushes.

**Comment by RonaldAJ** [comment]
>     * we don't push directly, but post PRs for review. an exception to that can be pre-approved and/or obviously trivial changes, like this one.
> 
>     * i'm a big fan of good commit hygiene. i'd use https://wiki.qt.io/Commit_Policy (as far as applicable) as a baseline, in particular point 8.

I might need some guidance here and there, but using PRs I think it can provided in the feedback on the PRs.

**Comment by ossilator** [comment]
speaking of forced pushes ....
what do you guys think of some revisionism?

background is that the squash merge of #123 really bothers me; it really didn't help understanding how the code evolved (and with 1,5 years distance that was actually necessary).

to be clear, the idea is _not_ to excise any functional mistakes, but just to make the history more legible.

so here's what i would do:
- rewind to right before the squash merge
- re-merge without squashing (that's actually a fast-forward)
- cherry-pick the commit tagged as 0.10.0
- re-tag
- rebase the newer history on top
  - optionally properly atomize lars' attempts to fix my mess

that's in line with my philosophy "make the history useful, not accurate", due to which i extensively rewrite local history, as per my previous comment. extending this to the published history would be an exception due to the perceived gravity.

of course, a forced push would have consequences:
- the tag would be invalidated, but i don't think anyone would care, as it's not signed anyway. the tagged content would be the same, so we wouldn't falsify the release.
- everyone with a somewhat up-to-date local clone would need to hard-reset their HEAD. that's presumably just the three of us.
- everyone with pending local work would need to rebase it. is that actually anyone except me?

WDYT?

**Comment by larsimmisch** [comment]
I am very fond of that idea! The squashed commit _was_ a mistake and your suggestion sounds like it would restore the historical dimension of this project.

Pending local work: I have some outstanding work for/around `loopback.py`. I have pushed that to a branch (`larsimmisch/loopback`) and would rebase it to `main` after a hard reset (and then open a PR for review for said work).

@RonaldAJ do you have pending local work?

**Comment by larsimmisch** [comment]
@ossilator I _think_ you should be able to force-push to `main` now, if the `--force` fails, let me know.

**Comment by RonaldAJ** [comment]
I had to force push to my own fork. It required me to temporarily disable my branch protection rules for the repo in the Github repo settings. (I also had to tell SmartGit to allow this.)

Security wise it might be best if Lars creates a new branch for the current main, lift branch protection and reset main to https://github.com/larsimmisch/pyalsaaudio/commit/19c9ba3ed9444e02a6d91b8650a21d6f9169fe66. And then restoring branch protection.

**Comment by ossilator** [comment]
don't worry about the particulars, i'm already on it.

**Comment by RonaldAJ** [comment]
Judging from the Forks page max 2 forks on top of ours are affected.

**Comment by RonaldAJ** [comment]
@ubifred, @julianfl0w the main branch of pyalsaaudio will be force changed. See discussion above.

**Comment by ossilator** [comment]
lars, i wonder how far i should go with the history cleanup?
specifically, #133 and #134 are sort of "in the way", in that they'll be falsified.
the sha1 mentioned in #133 can be adjusted, but #134 would have to be rebased to remain meaningful at all, which seems a bit silly.

so the easiest way would be to just squash the mess, mention the rewrite and related fixes in the new commit message, and add comments to the two pages.
i'll push a pre-rebase copy of main for posterity, so the original sha1s on github will remain somewhat relevant.

**Comment by RonaldAJ** [comment]
Conceptually there are at least two changes. But that being said the scope issue is very visible. I think that as you proposed squashing them and mentioning the issues and original sha1's in the submit message should do. Alternative would be to make 2 or 3 truly atomic and correct changes.

I think there are good reasons to simplify the history here.

**Comment by ossilator** [comment]
i can't actually produce _correct_ changes without going all in with the revisionism (to the point of changing the end state, not just the history), which i think we shouldn't do. but i think i've found a good compromise between historical accuracy and cleanliness, doing some partial squashing. i'll push soon.

**Comment by ossilator** [comment]
ok, it's done. :sunglasses:

**Comment by RonaldAJ** [comment]
Big thank you!

**Comment by ossilator** [comment]
lars, how about enabling discussions in the project settings? that's kind of the modern equivalent to a project mailing list. then we wouldn't have to further hijack this issue for the "meta" discussion, and users would hopefully ask questions there, rather than creating issues (you probably noticed that i closed all issues of this kind, as they are not action items for the development team).

**Comment by ossilator** [comment]
> I still had a fix for issue #110 pending. Which was adding the text:

that's a good addition, but i just noticed that much of this info is already in the documentation of ... info(). :joy: 
i'll pick it up and eliminate the redundancy.

**Comment by larsimmisch** [comment]
I've enabled discussions, good idea.

And another big thank you from me for cleaning up the issues and the history!
