### ISSUE TITLE
write not PCM but ADAT/DSP

### ISSUE THREAD

**Issue by Menogus** [larsimmisch/pyalsaaudio#15]
i have soundcard with 16 DSP Inputs
_inp = alsaaudio.PCM(alsaaudio.PCM_CAPTURE)_ write only PCM inputs
but i need to write thru DSP connected with ADAT
if i write in DEBIAN terminal:
_arecord --device=plughw:CARD=EMU1010,DEV=2 aaa.wav_
this command record 8 DSP channels normally
but how to do same in python?
because i need to process all channels like in this link: 
http://stackoverflow.com/questions/6867675/audio-recording-in-python

**my soundcard inputs:**
pulse
    PulseAudio Sound Server
default:CARD=EMU1010
    E-mu 1010 PCIe [MAEM8986], ADC Capture/Standard PCM Playback
    Default Audio Device
sysdefault:CARD=EMU1010
    E-mu 1010 PCIe [MAEM8986], ADC Capture/Standard PCM Playback
    Default Audio Device
front:CARD=EMU1010,DEV=0
    E-mu 1010 PCIe [MAEM8986], ADC Capture/Standard PCM Playback
    Front speakers
rear:CARD=EMU1010,DEV=0
    E-mu 1010 PCIe [MAEM8986], ADC Capture/Standard PCM Playback
    Rear speakers
center_lfe:CARD=EMU1010,DEV=0
    E-mu 1010 PCIe [MAEM8986], ADC Capture/Standard PCM Playback
    Center and Subwoofer speakers
side:CARD=EMU1010,DEV=0
    E-mu 1010 PCIe [MAEM8986], ADC Capture/Standard PCM Playback
    Side speakers
surround21:CARD=EMU1010,DEV=0
    E-mu 1010 PCIe [MAEM8986], ADC Capture/Standard PCM Playback
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=EMU1010,DEV=0
    E-mu 1010 PCIe [MAEM8986], ADC Capture/Standard PCM Playback
    4.0 Surround output to Front and Rear speakers
surround41:CARD=EMU1010,DEV=0
    E-mu 1010 PCIe [MAEM8986], ADC Capture/Standard PCM Playback
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=EMU1010,DEV=0
    E-mu 1010 PCIe [MAEM8986], ADC Capture/Standard PCM Playback
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=EMU1010,DEV=0
    E-mu 1010 PCIe [MAEM8986], ADC Capture/Standard PCM Playback
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=EMU1010,DEV=0
    E-mu 1010 PCIe [MAEM8986], ADC Capture/Standard PCM Playback
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
iec958:CARD=EMU1010,DEV=0
    E-mu 1010 PCIe [MAEM8986], ADC Capture/Standard PCM Playback
    IEC958 (S/PDIF) Digital Audio Output
dmix:CARD=EMU1010,DEV=0
    E-mu 1010 PCIe [MAEM8986], ADC Capture/Standard PCM Playback
    Direct sample mixing device
dmix:CARD=EMU1010,DEV=1
    E-mu 1010 PCIe [MAEM8986], Mic Capture
    Direct sample mixing device
dmix:CARD=EMU1010,DEV=2
    E-mu 1010 PCIe [MAEM8986], Multichannel Capture/PT Playback
    Direct sample mixing device
dsnoop:CARD=EMU1010,DEV=0
    E-mu 1010 PCIe [MAEM8986], ADC Capture/Standard PCM Playback
    Direct sample snooping device
dsnoop:CARD=EMU1010,DEV=1
    E-mu 1010 PCIe [MAEM8986], Mic Capture
    Direct sample snooping device
dsnoop:CARD=EMU1010,DEV=2
    E-mu 1010 PCIe [MAEM8986], Multichannel Capture/PT Playback
    Direct sample snooping device
hw:CARD=EMU1010,DEV=0
    E-mu 1010 PCIe [MAEM8986], ADC Capture/Standard PCM Playback
    Direct hardware device without any conversions
hw:CARD=EMU1010,DEV=1
    E-mu 1010 PCIe [MAEM8986], Mic Capture
    Direct hardware device without any conversions
hw:CARD=EMU1010,DEV=2
    E-mu 1010 PCIe [MAEM8986], Multichannel Capture/PT Playback
    Direct hardware device without any conversions
plughw:CARD=EMU1010,DEV=0
    E-mu 1010 PCIe [MAEM8986], ADC Capture/Standard PCM Playback
    Hardware device with all software conversions
plughw:CARD=EMU1010,DEV=1
    E-mu 1010 PCIe [MAEM8986], Mic Capture
    Hardware device with all software conversions
plughw:CARD=EMU1010,DEV=2
    E-mu 1010 PCIe [MAEM8986], Multichannel Capture/PT Playback
    Hardware device with all software conversions

**Comment by larsimmisch** [comment]
You'd need do something like:
```
pcm = alsaaudio.PCM(device='plughw:CARD=EMU1010,DEV=2')
pcm.setchannels(8)
pcm.setrate(44100)
pcm.setformat(alsaaudio.PCM_FORMAT_S16_LE)
```

and then read from `pcm`, like in `recordtest.py`. 

Note that this will not generate a wav file, but just the raw, probably interleaved audio as produced by the soundcard.
