### ISSUE TITLE
recordtest.py always record 8000 rate

### ISSUE THREAD

**Issue by kazimk** [larsimmisch/pyalsaaudio#16]
I want to record 48000 rate 32bit signed little endian sound but when I change values according to this.I only hear ringing.When I use default values it create a file with blank input and 8000 rate 8bit wav file.I am newbie on python programming on raspberry pi. I am sorry for asking this in issue section.What am I doing wrong?Thanks for help!

**Comment by larsimmisch** [comment]
Unfortunately, this issue tracker (i.e. me) is not a good resource for newbie questions and I do not really have a good resource to direct you to.

Anyway, I suspect that you are not using the correct device for your setup. Have a look at the available capture devices with `amixer` and try to make a recording with `arecord`. Once that is working, `recordtest.py` should also do what you want.
