### ISSUE TITLE
first time using audio on raspberry pi, test.py failing

### ISSUE THREAD

**Issue by interwebjill** [larsimmisch/pyalsaaudio#17]
Hello,

I have not worked with audio on the Raspberry Pi much. I have installed alsaaudio and have gotten this error:

pi@raspberrypi:/ $ python ./usr/share/doc/python-alsaaudio/examples/test.py
...E..
======================================================================
ERROR: testPCM (__main__.PCMTest)
Open a PCM object on every card
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./usr/share/doc/python-alsaaudio/examples/test.py", line 91, in testPCM
    pcm = alsaaudio.PCM(i)
ALSAAudioError: No such file or directory

----------------------------------------------------------------------
Ran 6 tests in 0.026s

FAILED (errors=1)

Can anyone point me in the right direction? Thanks.

**Comment by larsimmisch** [comment]
I wouldn't worry about that one. I think this is an artifact of the default RPi Alsa configuration. I'll get a new Pi soon and will have a look at it then.
