### ISSUE TITLE
Mixer.setvolume is nonlinear

### ISSUE THREAD

**Issue by sukovec** [larsimmisch/pyalsaaudio#22]
Hello. I'm trying to control volume with your library. But, I have a little problem here: volume setting is not linear. 

For example, when I call .setvolume(99, 0), in Alsamixer its displayed at bottom as 91 (-2.56dB). If I understand correctly, setvolume shall set the same value as is shown in Alsamixer at bottom. 

The soundcard I'm using is M-Audio Fast Track Ultra 8R. If you want, I can create some way for you to try it. 

Anyway, your library is still better than original ALSA API :)

**Comment by larsimmisch** [comment]
This is probably the same issue as #8

**Comment by quantenschaum** [comment]
Have a look #8, I explained the details there.
