### ISSUE TITLE
PCM plays two times faster

### ISSUE THREAD

**Issue by Lzrnk** [larsimmisch/pyalsaaudio#28]
It looks like setrate() dosn't work.
playwav.py plays test file two times faster than should do.
Changing rate with setrate() doesn't effect on playing rate.

**Comment by larsimmisch** [comment]
Twice as fast sounds a bit like the number of channels, like you have a mono file, but the wav header thinks it's stereo.

In any case, I think the problem is not `setrate`, but more like a strange wav header in your data.

**Comment by Lzrnk** [comment]
Thank you for the answer and very useful project.
[test3.wav.zip](https://github.com/larsimmisch/pyalsaaudio/files/795872/test3.wav.zip)


I've checked my file and haven't seen nothing special.
Yes it's mono, but  pcm.getnchannels() retuns 1 as it should be.
Also Audacity and pymedia play  this files without any problem.

**Comment by larsimmisch** [comment]
Hmmm. The Python `wave` module also shows it's mono:
```
>>> import wave
>>> w = wave.open('test3.wav')
>>> w.getnchannels()
1
>>> w.getframerate()
48000
```

I'll have to try to reproduce this bug here (don't hold your breath)

**Comment by larsimmisch** [comment]
I can not reproduce this. The file does sound fast (like from a TTS with no prosody), but it sounds the same on my Mac, through `aplay` and through `playwav.py`.

Also, the file should play for roughly 6 seconds according to the filesize (576044 / 48000 / 2)
