### ISSUE TITLE
Undefined behavior for read()

### ISSUE THREAD

**Issue by chriskuech** [larsimmisch/pyalsaaudio#31]
```
import alsaaudio
mic = alsaaudio.PCM(type=alsaaudio.PCM_CAPTURE, device='hw:1,0')
mic.setperiodsize(44100 / 60)
while True:
    (n, data) = mic.read()
```

When run on Raspbian, sometimes `n == -32`, which is undefined behavior according to the documentation

**Comment by larsimmisch** [comment]
-32 looks like `BROKEN_PIPE`.

**Comment by JohnCC330** [comment]
Just hit the same issue:

This is actually documented in the comments of [alsaaudio.c](https://github.com/larsimmisch/pyalsaaudio/blob/master/alsaaudio.c). However, the [Documentation](https://larsimmisch.github.io/pyalsaaudio/libalsaaudio.html#module-alsaaudio) does not mention this (maybe it should?)

> In case of an overrun, this function will return a negative size: -EPIPE.\n\
> This indicates that data was lost, even if the operation itself succeeded.\n\
> Try using a larger periodsize");
>

**Comment by larsimmisch** [comment]
Yes, the documentation should mention that. It's a nasty pitfall.

Every time I stumble across this, I think: we should really throw an exception in this case. But it isn't an unrecoverable error, and throwing an exception would make the data loss worse, so that's not the right thing either.

**Comment by larsimmisch** [comment]
Fixed (i.e. documented) in adc0d800e1e9547c351151fc1135a62fc2f66351

**Comment by JohnCC330** [comment]
Thanks, Lars!
