### ISSUE TITLE
setperiodsize does't work

### ISSUE THREAD

**Issue by Lzrnk** [larsimmisch/pyalsaaudio#34]
I run this script
and it returns the same number for all PCM.read  - it's 341
but as I understood from description it should be 500, 1000 and 2000

`#!/usr/bin/env python
import alsaaudio
ASOURCE = "default:CARD=PCH"
rec = alsaaudio.PCM(alsaaudio.PCM_CAPTURE, device=ASOURCE)
rec.setchannels(1)
rec.setrate(16000)
rec.setformat(alsaaudio.PCM_FORMAT_S16_LE)

rec.setperiodsize(500)
length, data = rec.read()
print('frames captured: {0}'.format(length))

rec.setperiodsize(1000)
length, data = rec.read()
print('frames captured: {0}'.format(length))

rec.setperiodsize(2000)
length, data = rec.read()
print('frames captured: {0}'.format(length))
`

**Comment by bewantbe** [comment]
"The hardware parameters cannot be changed when the stream is running (active)." [Ref]

"periodsize" is one of the hardware parameters. After the first rec.read(), it is in running state.

use rec.dumpinfo() to check the state (the line start with "PCM state")

Ref: [ALSA project - the C library reference - PCM Interface - snd_pcm_hw_params](https://www.alsa-project.org/alsa-doc/alsa-lib/group___p_c_m.html#ga1ca0dc120a484965e26cabf966502330)
