### ISSUE TITLE
Help for implement `aplay -l` - List audio interfaces

### ISSUE THREAD

**Issue by SrMouraSilva** [larsimmisch/pyalsaaudio#36]
Hello, I would like a help for me to implement the similar feature to `aplay -l`.
Could you guide me?

Contextualization: I need in my application to list the audio interfaces. Do something like `qjackctrl`. I found a solution to manually pick up from `aplay -l`, but this raises problems in linux with other defined languages.

![image](https://cloud.githubusercontent.com/assets/5341804/25855553/e02eda68-34a9-11e7-9f91-f9c9552054ee.png)

**Comment by larsimmisch** [comment]
Please have a look at https://larsimmisch.github.io/pyalsaaudio/libalsaaudio.html

`alsaaudio.pcms(alsaaudio. PCM_CAPTURE)` is roughly equivalent to `aplay -L`, not sure how to get the result of `aplay -l`

**Comment by SrMouraSilva** [comment]
Hi, thanks for your feedback.

I had already checked the use of `alsaaudio.pcms`. However, it (which corresponds to `aplay -L`) does not enumerate the audio interfaces. I need something similar to `aplay -l`.

I intended to support your project by adding this functionality. But since I have no idea how to get this information and you do not, unfortunately I will not be able to contribute.
