### ISSUE TITLE
Missing git tags for 0.8.3 and 0.8.4

### ISSUE THREAD

**Issue by carstene1ns** [larsimmisch/pyalsaaudio#37]
Hi, I am packaging pyalsaaudio for Arch Linux User Repository:
https://aur.archlinux.org/packages/python-pyalsaaudio/
This package was flagged out of date lately, despite me monitoring the git tags of this repository.
I missed the new versions 0.8.3 and 0.8.4, because they were not tagged.

So please add the missing git tags for 0.8.3 and 0.8.4. Thanks!

---

*A bit of background story:*
Reason I use this is because GitHub provides a nice, clean source URL, e.g.
`https://github.com/larsimmisch/pyalsaaudio/archive/0.8.4.tar.gz`
Using the source download from pypi is bad IMO, because they provide an ugly, hashed URL, e.g.
`https://pypi.python.org/packages/52/b6/44871791929d9d7e11325af0b7be711388dfeeab17147988f044a41a6d83/pyalsaaudio-0.8.4.tar.gz`

At least seems like others do not like this, too:
https://bitbucket.org/pypa/pypi/issues/438/backwards-compatible-un-hashed-package
At least they added now a redirector service, so using that for now:
https://files.pythonhosted.org/packages/source/p/pyalsaaudio/pyalsaaudio-0.8.4.tar.gz

**Comment by larsimmisch** [comment]
I've added the missing tags.
