### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by revatid** [larsimmisch/pyalsaaudio#40]
Getting following error while installation : 
alsaaudio.c:28:10: fatal error: 'alsa/asoundlib.h' file not found
#include <alsa/asoundlib.h>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
error: command 'cc' failed with exit status 1

Ways to reproduce : 
1. Already have gcc  : 
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

2. sudo pip install pyalsaaudio

OS : Mac

**Comment by larsimmisch** [comment]
Missing prerequisites (libasound-dev or similar)
