### ISSUE TITLE
Invalid argument on initializing PCM

### ISSUE THREAD

**Issue by hikavdh** [larsimmisch/pyalsaaudio#5]
Iḿ still running 0.7-r2 as installed from Gentoo. I suspect it having to do with pulseaudio running. The error is triggered by the card argument, set to a value supplied by the cards() function. On other machine not running pulse it works OK. I'm looking at  creating an ebuild to install 0.8 and test therewith.

**Comment by larsimmisch** [comment]
Yes, that's a known issue with 0.7 (in certain configurations). Do try 0.8.2 and use a value from the new `pcms()` function to open a PCM device.

Using a value from `cards()` does not work in all configurations, see https://github.com/larsimmisch/pyalsaaudio/blob/master/CHANGES
