### ISSUE TITLE
playwav.py demo not working(setperiodsize not accepting floating point)

### ISSUE THREAD

**Issue by moham96** [larsimmisch/pyalsaaudio#54]
Hi,
the demo that comes with the library is not working

> Traceback (most recent call last):
>   File "playwav.py", line 63, in <module>
>     play(device, f)
>   File "playwav.py", line 35, in play
>     device.setperiodsize(periodsize)
> TypeError: integer argument expected, got float

**Comment by adaptiman** [comment]
A can confirm this behavior on Raspbian 2018-03-13.

**Comment by larsimmisch** [comment]
PR is merged, closing.
