### ISSUE TITLE
Documentation does not clearly indicate types of inputs and outputs

### ISSUE THREAD

**Issue by madphysicist** [larsimmisch/pyalsaaudio#58]
Reading the docs, it is very difficult to be certain about the types of outputs, and even more so the expected inputs. An example is here: https://stackoverflow.com/q/49890368/2988730. The prime example is [`setvolume`](https://larsimmisch.github.io/pyalsaaudio/libalsaaudio.html#alsaaudio.Mixer.setvolume). Does it normally accept an integer or a list? It seems to be an integer, but then how does interact with the different channels.

This is related to #48, where the meaning rather than the type of the output is in question.

**Comment by SchulerSimon** [comment]
This is also a problem with Type Checking done by pylint: 

![grafik](https://github.com/larsimmisch/pyalsaaudio/assets/36367814/75790f82-12ea-4fa5-a837-b713016c6434)
![grafik](https://github.com/larsimmisch/pyalsaaudio/assets/36367814/70a5f7d5-9c57-4520-9c97-2a250e7df72c)

To reproduce, enable "strict" for Type Checking (assuming Visual Studio Code and pylint). 

```python
def setup_alsa_output_stream(self):
    """uses the python-wrapper for ALSA to setup an output stream for audio"""
    output_stream = alsaaudio.PCM(  # type: ignore 
        alsaaudio.PCM_PLAYBACK,  # type: ignore 
        alsaaudio.PCM_NORMAL,  # type: ignore 
        rate=self.rate,
        channels=self.channels,
        periodsize=int(self.frames_per_buffer / 2),
        device="plug:airplay",
    )

    while self.audio_streams_started:
        raw_data = self.output_buffer.get(self.frames_per_buffer * 2)
        output_stream.write(raw_data)  # type: ignore 
```

Note the # type: ignore at the end of too many lines.

**Comment by larsimmisch** [comment]
Take a look at https://github.com/larsimmisch/pyalsaaudio/pull/136. Does this improve things?
