### ISSUE TITLE
Missing function to set enumerated values in Mixer

### ISSUE THREAD

**Issue by hikavdh** [larsimmisch/pyalsaaudio#6]
For now I have to use amixer to select a capture input.

**Comment by larsimmisch** [comment]
I don't understand this issue - please elaborate (and reopen)

**Comment by hikavdh** [comment]
You have enumerated mixer switches to for instance set the capture source; line, phone, etc. I can list the possible values with getenum(), but I can not set them. In other words I am missing the function setenum() or something like that. I have to use amixer in my code e.g.:  
check_call(['amixer', '--quiet', '--card=%s' % self.get_cardid(), 'sset', '"%s"'  % (config.opt_dict['source_switch']), config.opt_dict['source']])

**Comment by larsimmisch** [comment]
This was done in #27
