### ISSUE TITLE
PCM.setchannels() not working on playback device

### ISSUE THREAD

**Issue by theo-basty** [larsimmisch/pyalsaaudio#61]
I ran in a very strange problem recently. I had a fully working code that I didn't touched and which suddenly stopped working for no reason (I tried it with exactly the same hardware configuration than earlier but nothing....)
In this code, I need to record some sound from an usb sound card and play it on the same sound card. Due to the audio devices I use, I only need 1 channel and so I configured my PCMs like that : 

`        #INPUT
        self.inp = alsaaudio.PCM(alsaaudio.PCM_CAPTURE, alsaaudio.PCM_NORMAL, device=device)
        self.inp.setchannels(1)
        self.inp.setrate(44100)
        self.inp.setformat(alsaaudio.PCM_FORMAT_S16_LE)
        self.inp.setperiodsize(640)

        #OUTPUT
        self.out = alsaaudio.PCM(alsaaudio.PCM_PLAYBACK, device=device)
        self.out.setchannels(1)
        self.out.setrate(44100)
        self.out.setformat(alsaaudio.PCM_FORMAT_S16_LE)
        self.out.setperiodsize(160)`

After some research in alsa, found out that the playback device was set to dual channels even if it I changed it.

`$ more /proc/asound/card1/pcm0c/sub0/hw_params
access: RW_INTERLEAVED
format: S16_LE
subformat: STD
channels: 1
rate: 44100 (44100/1)
period_size: 640
buffer_size: 2560

$ more /proc/asound/card1/pcm0p/sub0/hw_params
access: RW_INTERLEAVED
format: S16_LE
subformat: STD
channels: 2
rate: 44100 (44100/1)
period_size: 160
buffer_size: 640`

I fixed my problem by using them in dual channel but I'd prefer to work in mono channel, and if it's a bug it should be fixed...

**HARDWARE**
`Raspberry pi 3
Raspbian 4.9.80-v7+ #1098 SMP Fri Mar 9 19:11:42 GMT 2018 armv7l GNU/Linux
USB sound card:
  T:  Bus=01 Lev=02 Prnt=02 Port=03 Cnt=02 Dev#=  4 Spd=12   MxCh= 0
  D:  Ver= 1.10 Cls=00(>ifc ) Sub=00 Prot=00 MxPS= 8 #Cfgs=  1
  P:  Vendor=8086 ProdID=0808 Rev= 1.00
  S:  Manufacturer=C-Media Electronics Inc.
  S:  Product=USB PnP Sound Device`

**Comment by larsimmisch** [comment]
This should be fixed in 0.9.0
