### ISSUE TITLE
Unintentional commit revert?

### ISSUE THREAD

**Issue by follower** [larsimmisch/pyalsaaudio#62]
While investigating an issue I noticed this change to `alsapcm_setperiodsize()`...:

* "Update periodsize only after `alsapcm_setup` succeeded" <https://github.com/larsimmisch/pyalsaaudio/commit/1aae655d24339d3fd07e7a98c64b867365202dff>

...appears to be reverted by the next commit:

* "Transactional semantics for the alsapcm_set* calls"
<https://github.com/larsimmisch/pyalsaaudio/commit/25717020efe1fea939fe0a6e291109b6bd4bfa26#diff-c173c43425f546cb50e217c77dda54b5R754>

Was this intentional?

But also, isn't `self->periodsize` already set here: <https://github.com/larsimmisch/pyalsaaudio/blob/25717020efe1fea939fe0a6e291109b6bd4bfa26/alsaaudio.c#L346>

**Comment by larsimmisch** [comment]
That was intentional, yes, to preserve the previous value of periodsize if setting the hardware params failed (because maybe a playback/recording is in progress)
