### ISSUE TITLE
Clarification to the mixer.getrange() function

### ISSUE THREAD

**Issue by not-sekiun** [larsimmisch/pyalsaaudio#71]
If we take mixer as the Alsaaudio mixer object, what is the range that the mixer.getrange() function obtains? What do the 2 numbers within the returned list signify. Are they percentage ranges? Decibel ranges?

**Comment by crocket** [comment]
It's decibel ranges, but the signs are reversed.

**Comment by larsimmisch** [comment]
Resolved by #109
