### ISSUE TITLE
TypeError at setperiodsize()

### ISSUE THREAD

**Issue by borley1211** [larsimmisch/pyalsaaudio#74]
# My Env
* OS: ``Ubuntu 18.04 LTS`` (on ``WSL``)
* ``python``: 3.7.3 (using ``pipenv``)
* ``ALSA``: 
  * default device: ``pulse`` (``PulseAudio``)
  * format: S16_LE, 96000Hz

# Issue
When running ``playwav.py``, python raised TypeError.
The log was  as follows...

```terminal
TypeError: integer argument expected, got float
```

# Solution
That error was solved when modifying ``playwav.py`` from

```python: before
33 |    periodsize = f.getframerate() / 8  # type(periodsize) = 'int' or 'float'
34 |
35 |    device.setperiodsize(periodsize)
```

to

```python:after
33 |    periodsize = f.getframerate() // 8  # type(periodsize) = 'int'
34 |
35 |    device.setperiodsize(periodsize)  # setperiodsize() always receive variable having an integer-type!
```

**Comment by miccoli** [comment]
same as #54
