### ISSUE TITLE
Unplugging a USB DAC freezes alsaaudio.PCM and the system.

### ISSUE THREAD

**Issue by crocket** [larsimmisch/pyalsaaudio#77]
Whenever I play audio, opening the USB DAC takes 500 milliseconds. Thus, I use the following program to keep my USB DAC open.

```
#!/usr/bin/env python
import alsaaudio
import time
import sys

if __name__ == "__main__":
  device=alsaaudio.PCM(device=sys.argv[1])
  while True:
    time.sleep(1)
```

If I unplug the USB DAC while the program is running and try to kill the program with SIGTERM, the program becomes an immortal zombie process that cannot be killed. After it becomes a zombie process, my system freezes within a minute or two. Keyboard and mouse stop working very soon.

On the other hand, SIGINT(Ctrl+C) can kill the program after unplugging the USB DAC.

**Comment by larsimmisch** [comment]
I'm afraid there is nothing pyalsaaudio can do there. It installs no signal handlers. As a general rule of thumb, a user-level binary should not be able to crash a system - the problem is probably a faulty driver.

**Comment by crocket** [comment]
You mean snd-usb-audio.
