### ISSUE TITLE
PCM.pause(enable=1) method raises an error 

### ISSUE THREAD

**Issue by RogerPallares** [larsimmisch/pyalsaaudio#79]
I would like to use the pause() method in my code, but all the time I call this method an error appears. The main code is:

```
import alsaaudio
CHANNELS    = 1
INFORMAT    = alsaaudio.PCM_FORMAT_S16_LE
RATE        = 44100
 FRAMESIZE   = 100

recorder = alsaaudio.PCM(alsaaudio.PCM_CAPTURE, alsaaudio.PCM_NORMAL, device='plughw:1')
recorder.setchannels(CHANNELS)
recorder.setrate(RATE)
recorder.setformat(INFORMAT)
recorder.setperiodsize(FRAMESIZE)
recorder.pause(enable=1)
```

Which gives me the error:
>  TypeError: pause() takes no keyword arguments

On the other hand, if I only write `recorder.pause()` or `recorder.pause(1)`, I get the following error:
> ALSAAudioError: File descriptor in bad state [plughw:1]

Any ideas about why this is happening?

**Comment by larsimmisch** [comment]
The correct way to pause is to call `pause(1)`, but - from https://www.alsa-project.org/alsa-doc/alsa-lib/group___p_c_m.html#gad711b582c7066bd4fffa1d08a04316b5:

> Note that this function works only on the hardware which supports pause feature

I suspect your hardware doesn't support the pause feature.
