### ISSUE TITLE
setvolume/getvolume methods is not bound directly

### ISSUE THREAD

**Issue by stalkerg** [larsimmisch/pyalsaaudio#84]
For example, we have control with range 0, 87 if we will use setvolume(50) the getvolume() return to us 51. 
It's happening because we are using rint in this method. 
Probably it's possible to fix by different round function but I suppose also important to provide solution to setup raw numbers for volume/gain. 

Thanks.

**Comment by larsimmisch** [comment]
In hindsight, I suspect it would have made more sense to use floating point values between 0.0 and 1.0 (or just dB values throughout), but that ship has sailed.

**Comment by stalkerg** [comment]
Why sailed? We can add setvolumef/getvolumef it's really help a lot me.
