### ISSUE TITLE
Record quality very low

### ISSUE THREAD

**Issue by el07694** [larsimmisch/pyalsaaudio#85]
Well i tried the recordtest.py script.

The output is:

[output_file.zip](https://github.com/larsimmisch/pyalsaaudio/files/4745271/output_file.zip)

Well with aplay -r 44100 -f S16_LE -c 1 output.raw the quality is very low.
Same quality while importing raw data file in Audacity.

What can i do?

Thanks in advance,
Chris Pappas

**Comment by larsimmisch** [comment]
That's royally distorted, but I have no clue why, sorry.
