### ISSUE TITLE
How can i use pyalsaaudio for radio streaming?

### ISSUE THREAD

**Issue by el07694** [larsimmisch/pyalsaaudio#86]
As the title says, how can i use pyalsaaudio module to send mp3 radio for radio transmition use python-shout module? (reference: https://stackoverflow.com/questions/5303445/creating-multiple-audio-streams-of-an-icecast2-server-using-python-shout

**Comment by larsimmisch** [comment]
I don't understand the question. If you want to send mp3s using python-shout, pyalsaaudio is just the wrong tool - it is just an interface to ALSA (i.e. the local soundcards)
